replicaCount: 1

image:
  repository: buildinglink/fitnessweekly
  pullPolicy: IfNotPresent
  tag: "1.8.5"

service:
  port: 3000
  type: ClusterIP

hostPort: 3000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
  BLDBPRO: aware
  BLRANCHER: https://rancher.buildinglink.com

resources: {}
#  limits:
#    cpu: 100m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
